headers:
  all: # Header rules for all subgraphs
    request:
      - propagate:
          matching: ^* # Propagate all headers
include_subgraph_errors:
  all: true # Propagate errors from all subgraphs