// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type MovieTrailers struct {
	Title    string   `json:"title"`
	Trailers []string `json:"trailers"`
}

func (MovieTrailers) IsEntity() {}
